services:
    hia_session.record:
        class: HIA\UserBundle\RecordSession\RecordSession
        arguments: [@doctrine.orm.entity_manager, @session]

    hia_session.listener:
            class: HIA\UserBundle\ConnectListener\ConnectListener
            arguments: [@hia_session.record]
            tags:
                - { name: kernel.event_listener, event: security.interactive_login, method: processLogin }
