hia_form:
    resource: "@HIAFormBundle/Controller/"
    type:     annotation
    prefix:   /

hia_core:
    resource: "@HIACoreBundle/Controller/"
    type:     annotation
    prefix:   /

hia_user:
    resource: "@HIAUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout