# app/config/security.yml

security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        HIA\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: HIA\UserBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            anonymous: true

        forgetPassword:
            pattern: ^/account/forgetPassword$
            anonymous: true

        main:
            pattern:   ^/
            anonymous: false
            provider:  main
            form_login:
                login_path: HIAUserLogin
                check_path: login_check

    access_control:
        # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
