<?php

namespace HIA\FormBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * FormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormRepository extends EntityRepository
{
    // Retourne tous les formulaires
    public function getAll($idUser, $offset, $limit)
    {
        $qb = $this->createQueryBuilder('f')
                    ->leftJoin('f.tags', 't')
                    ->addSelect('t')
                    ->orderBy('f.dateCreate', 'DESC')
                    ->leftJoin('f.writers', 'g')
                    ->leftJoin('g.users', 'u')
                    ->where('u.id = :idUser')
                    ->setParameter("idUser", $idUser)
                    ->setFirstResult($offset)
                    ->setMaxResults($limit);

        $results = new Paginator($qb, true);

        return $results->getQuery()->getResult();
    }

    // Retourne tous les formulaires avec des contraintes
    public function getForms($idUser, $formName, $idTags, $offset, $limit)
    {
        // TODO Bug quand on deselectionne les 2 premier tag l'ordre d'affichage change
        $qb = $this->createQueryBuilder('f')
                    ->leftJoin('f.tags', 't')
                    ->orderBy('f.dateCreate', 'DESC')
                    ->leftJoin('f.writers', 'g')
                    ->leftJoin('g.users', 'u')
                    ->where('u.id = :idUser AND f.name LIKE :formName AND t.id IN (:tags)')
                    ->setParameters(array(
                            "idUser" =>  $idUser,
                            "formName" => "%" . $formName . "%",
                            "tags" => $idTags
                        ))
                    ->distinct()
                    ->setFirstResult($offset)
                    ->setMaxResults($limit);

        return $qb->getQuery()->getArrayResult();
    }

    // Compte le nombre de formulaire auquel l'utilisateur à accès
    public function countFormUserCanAccess($idUser)
    {
        $qb = $this->createQueryBuilder('f')
                    ->select("COUNT(f)")
                    ->leftJoin('f.writers', 'g')
                    ->leftJoin('g.users', 'u')
                    ->where('u.id = :idUser')
                    ->setParameters(array(
                            "idUser" =>  $idUser,
                        ));

        return $qb->getQuery()->getSingleScalarResult();
    }

    // Compte le nombre de formulaire auquel l'utilisateur à accès selon certains critères
    public function countFormUserCanAccessAjax($idUser, $formName, $idTags)
    {
        $qb = $this->createQueryBuilder('f')
            ->select('COUNT(f)')
            ->leftJoin('f.tags', 't')
            ->orderBy('f.dateCreate', 'DESC')
            ->leftJoin('f.writers', 'g')
            ->leftJoin('g.users', 'u')
            ->where('u.id = :idUser AND f.name LIKE :formName AND t.id IN (:tags)')
            ->setParameters(array(
                "idUser" =>  $idUser,
                "formName" => "%" . $formName . "%",
                "tags" => $idTags
            ));

        return $qb->getQuery()->getSingleScalarResult();
    }

    // Retourne 1 ou plus si l'utilisateur peut utiliser le formulaire
    public function canUse($idUser, $idForm)
    {
        $qb = $this->CreateQueryBuilder('f')
                    ->select("COUNT(f)")
                    ->leftJoin("f.writers", 'g')
                    ->leftJoin("g.users", 'u')
                    ->where("u.id = :idUser AND f.id = :idForm")
                    ->setParameters(array(
                        "idUser" => $idUser,
                        "idForm" => $idForm
                    ));

        return $qb->getQuery()->getSingleScalarResult();
    }

    // Retourne un formulaire complet (groupe associé, champs, contrainte, ...)
    public function getCompleteForm($id)
    {
        $qb = $this->CreateQueryBuilder('f')
                    ->leftJoin('f.fields', 'fi')
                    ->leftJoin('f.tags', 't')
                    ->leftJoin('fi.defaultValues', 'd')
                    ->leftJoin('f.readers', 'g')
                    ->leftJoin('fi.fieldConstraints', 'c')
                    ->leftJoin('c.params', 'p')
                    ->select('f')
                    ->addSelect('fi')
                    ->addSelect('t')
                    ->addSelect('d')
                    ->addSelect('g')
                    ->addSelect('c')
                    ->addSelect('p')
                    ->where('f.id = :idForm')
                    ->setParameter('idForm', $id);

        return $qb->getQuery()->getOneOrNullResult();
    }

    // Retourne tous les formulaires
    public function getUsedForm($idUser)
    {
        $qb = $this->createQueryBuilder('f')
            ->leftJoin('f.writers', 'g')
            ->leftJoin('g.users', 'u')
            ->leftJoin('f.registrations', 'r')
            ->addSelect('r')
            ->where('u.id = :idUser')
            ->setParameter("idUser", $idUser);

        return $qb->getQuery()->getResult();
    }
}
