<?php

namespace HIA\UserBundle\Entity;

/**
 * JournalAccessRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalAccessRepository extends \Doctrine\ORM\EntityRepository
{
}
