<?php

namespace HIA\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends EntityRepository
{
    public function getCurrentSession($idUser)
    {
        $qb = $this->createQueryBuilder('s')
            ->where("s.user = :idUser AND s.logout is NULL")
            ->setParameters(array(
                'idUser' => $idUser
            ));

        return $qb->getQuery()->getResult();
    }
}
