<?php

namespace HIA\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function isExist($username)
    {
        $qb = $this->createQueryBuilder('u')
            ->select("COUNT(u)")
            ->where('u.username = :username')
            ->setParameters(array(
                "username" =>  $username,
            ));

        return $qb->getQuery()->getSingleScalarResult();
    }
}
